## Pegar as rodados com maior Reward

In [1]:
import numpy as np
from data_preprocessing import DataHandler
from make_video import VideoMaker
import matplotlib.pyplot as plt

In [12]:
rewards = np.load(r'../Datasets/tutorial_human_expert_0/rewards.npy')
states = np.load(r'../Datasets/tutorial_human_expert_0/states.npy')
actions = np.load(r'../Datasets/tutorial_human_expert_0/actions.npy')
actions = actions[:,0,:]

indices_maiores_valores = np.argsort(rewards[:, 1])[-20:][::-1]
start_and_end = np.array([[0] + (list(rewards[:-1,0]+1)), list(rewards[:,0])]).T[sorted(indices_maiores_valores)]
start_and_end

array([[    0,  1335],
       [ 8058,  9352],
       [19355, 20695],
       [20696, 22212],
       [22213, 25103],
       [25104, 26630],
       [28610, 29901],
       [36795, 38120],
       [40717, 41973],
       [41974, 43528],
       [43529, 44744],
       [44745, 46502],
       [50462, 52224],
       [54005, 55302],
       [55303, 56815],
       [56816, 58454],
       [58455, 60136],
       [65138, 66659],
       [68566, 69976],
       [69977, 71344]])

In [13]:
top_states = np.array([])
top_actions = np.array([])
counter = 0 
for index, ele in enumerate(start_and_end):
    if index == 0:
        top_states = states[ele[0]:ele[1]]
        top_actions = actions[ele[0]:ele[1]]
        counter += 1
    elif index == 4:  # Estranho
        continue
    else:
        top_states = np.concatenate([top_states, states[ele[0]:ele[1]]])
        top_actions = np.concatenate([top_actions, actions[ele[0]:ele[1]]])
        counter += 1
    video_maker = VideoMaker()
    video_maker.save_record(states[ele[0]:ele[1]], name='../Datasets/tutorial_human_expert_0_top_20/video'+str(index), origin='human')

print(top_states.shape)
print(top_actions.shape)

(27597, 96, 96, 3)
(27597, 3)


In [14]:
np.save(r'../Datasets/tutorial_human_expert_0_top_20/actions.npy', top_actions)
np.save(r'../Datasets/tutorial_human_expert_0_top_20/states.npy', top_states)

video_maker = VideoMaker()
array  = video_maker.load_array('../Datasets/tutorial_human_expert_0_top_20/states.npy')
video_maker.save_record(array, name='../Datasets/tutorial_human_expert_0_top_20/video', origin='human')

In [15]:
action_top_20 = np.load(r'../Datasets/human/tutorial_human_expert_0_top_20/actions.npy')
len(action_top_20)*250/64

107800.78125

## Transformar as ações do PPO de 2 dimensões em 3

In [39]:
actions = np.load(r'../Datasets/ppo/todos/acs_CarRacing-v0_seed=66_ntraj=20.npy')
actions

array([[-0.37100172,  1.0090537 ],
       [-1.377031  ,  2.0159955 ],
       [ 2.0790784 ,  1.341649  ],
       ...,
       [-0.9855932 ,  0.19670863],
       [ 0.33632326, -0.22087106],
       [ 0.6408633 ,  0.55993545]], dtype=float32)

In [36]:
def actions_2d_to_3d(path):
    actions_2d = np.load(path)

    if actions_2d.shape[1] == 2:
        actions_steering = actions_2d[:,0]
        actions_gas = [ele if ele > 0 else 0 for ele in actions_2d[:,1]]
        actions_brake = [-ele if ele < 0 else 0 for ele in actions_2d[:,1]]

        actions = np.array([actions_steering, actions_gas, actions_brake]).T
        np.save(path, actions)

In [40]:
actions_2d_to_3d(r'../Datasets/ppo/todos/acs_CarRacing-v0_seed=66_ntraj=20.npy')
actions_2d_to_3d(r'../Datasets/ppo/todos/acs_CarRacing-v0_seed=68_ntraj=20.npy')

In [38]:
def invert_brake(path):
    actions_2d = np.load(path)

    actions_steering = actions_2d[:,0]
    actions_gas = actions_2d[:,1]
    actions_brake = [-ele for ele in actions_2d[:,2]]

    actions = np.array([actions_steering, actions_gas, actions_brake]).T
    np.save(path, actions)

invert_brake(r'../Datasets/ppo/tutorial_ppo_expert_68/actions.npy')
invert_brake(r'../Datasets/ppo/tutorial_ppo_expert_66/actions.npy')

In [24]:
rewards = np.load(r'../Datasets/human/tutorial_human_expert_0/rewards.npy')
states = np.load(r'../Datasets/human/tutorial_human_expert_0/states.npy')
actions = np.load(r'../Datasets/human/tutorial_human_expert_0/actions_orig.npy')
actions = actions.squeeze()
np.save(r'../Datasets/human/tutorial_human_expert_0/actions.npy', actions)

In [20]:
states = np.load(r'../Datasets/human/tutorial_human_expert_1/states.npy')
states.shape
states

array([[[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
        

In [19]:
states.shape
states

array([[[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
        